sonar.projectKey=sams-big-fake-company_legacy-payments
sonar.organization=sams-big-fake-company

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.source=11
sonar.sourceEncoding=UTF-8
